import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Common/Footer";
import QueryProvider from "./contexts/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <QueryProvider>
            <Toaster position="bottom-center" />
            <div className="font-raleway text-neutral">{children}</div>
          </QueryProvider>
        </AuthProvider>
      <Footer />
      </body>
    </html>
  );
}
